version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: notes_service
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./sql/mockdb.sql:/docker-entrypoint-initdb.d/mockdb.sql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
        
volumes:
  db_data:

