services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: notes_service
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./sql/mockdb.sql:/docker-entrypoint-initdb.d/mockdb.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notes_service -d notes"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
volumes:
  db_data: